### ISSUE TITLE
[TODO] Text Editor Updates

### ISSUE THREAD

**Issue by FireBanana** [FireBanana/ElaborateEditor#1]
The following features need to be implemented:

- [x] Add key repeat actions. (Currently nothing happens on repeat).
- [x] Allow mouse click to adjust cursor position accordingly.
- [ ] Add text highlighting.
- [ ] Add mouse drag highlighting.
- [x] Add tab spacing.
- [x] Add arrow movement to next or previous line.

Specfic key actions to be added:

**Ctrl**
- [ ] + Z (Undo)
- [ ] + A (Select All)
- [ ] + X (Cut)
- [ ] + V (Paste)

**Comment by FireBanana** [comment]
Arrow movement fixed in: https://github.com/FireBanana/ElaborateEditor/commit/3f34be3e4a7134e178a868470a93281071db2bc6

**Comment by FireBanana** [comment]
Mouse click cursor movement added in: https://github.com/FireBanana/ElaborateEditor/commit/6111ae1960a2911322b931ee723c96ac17d9cefb
